### PR TITLE
Fix typos and improve documents

### PR DESCRIPTION
**Pull request by shuuji3**
Hello,
I corrected the typo and grammatical errors to improve documents.
Also, I updated a few descriptions in the sample codes.

### CODE REVIEW

**Comment by yokotaso** [comment]
@shuuji3 Thank you for contribution! I will see it later :+1:

**Comment by shuuji3** [comment]
Thanks for reviewing!

Off-topic: I'm writing on JavaScript code on Kintone platform as a part-time job. And I had a schedule to rewrite our code base to TypeScript and I think I had to create Type Definition for `kintone` by myself. This library also helps us a lot even for JavaScript development. Thank you!

**Comment by yokotaso** [comment]
@shuuji3 
Because circleci workflow won't work well. I will survey it.
I will merge you PR. Thank you contribution! 

I am glad to hear your good impression!

**Comment by yokotaso** [comment]
@shuuji3 Thank you for great work! cheers!

**Pull request merged**
